version: "3"
networks:
    ds-wordpress-6.1.1-net:
        driver: bridge

services:
    mysql:
        # ... (sin cambios)

    server:
        image: wordpress:latest
        container_name: ds-wordpress-6.1.1
        ports:
            - "4282:443"
        volumes:
            - "./var/www/html/:/var/www/html"
            - "./certs:/etc/apache2/ssl"
        environment:
            WORDPRESS_DB_USER: locky
            WORDPRESS_DB_PASSWORD: admin1234*
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_HOST: ds-wordpress-6.1.1-mysql
            WORDPRESS_CONFIG_EXTRA: |
                define('FORCE_SSL_ADMIN', true);
                if ($_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') $_SERVER['HTTPS']='on';
        depends_on:
            - mysql
        networks:
            - ds-wordpress-6.1.1-net

    phpmyadmin:
        # ... (sin cambios)